apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: mandriic/java-app:9be3b3abe5e9781c3ab396e604a3726be74d0d7a
        ports:
        - containerPort: 8080
