apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: mandriic/java-app:5a98b98b2d0f1d122095cf2a254236af3203a4
        ports:
        - containerPort: 8080
