name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
        
    - name: Checkout repository
      uses: actions/checkout@v4
        

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'


    - name: Build with gradlew
      run: chmod +x ./gradlew && ./gradlew build
        
    - name: Archive Build Output
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build/libs/
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        ecr: false
        username: mandriic
        password:  dckr_pat_Qxkv_-x2FWykZYsTbyqfCp2WxUw
        #password:  ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image  
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: mandriic/java-app:latest
        build-args: |
          JAR_FILE=build/libs/demo-0.0.1-SNAPSHOT.jar
    #- name: Build and Push Docker Image
    #  uses: docker/build-push-action@v4
    #  with:
    #    push: true
    #    tags: mandriic/java-app:latest
