name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
        
    - name: Checkout repository
      uses: actions/checkout@v4
        

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'


    - name: Build with gradlew
      run: chmod +x ./gradlew && ./gradlew build
        
    - name: Archive Build Output
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build/libs/

    - name: Download Build Output
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: build/libs/
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        ecr: false
        username: mandriic
        password:  dckr_pat_Qxkv_-x2FWykZYsTbyqfCp2WxUw
        #password:  ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: mandriic/java-app:latest
        file: Dockerfile
        build-args: |
          JAR_FILE=build/libs/demo-0.0.1-SNAPSHOT.jar
          
    - name: Touch YAML file
      run: touch path/to/your/deployment.yaml

    - name: Commit and push changes to trigger Argo CD sync
      run: |
        git config --global user.email "kellaxxx@gmail.com"
        git config --global user.name "mandriic"
        git add k8s/java-app.yaml
        git commit -m "Touch YAML file to trigger Argo CD sync"
        git push origin main
    
  #  - name: Build and Push Docker Image  
  #    uses: docker/build-push-action@v4
  #    with:
   #     push: true
   #     tags: mandriic/java-app:latest
   #     build-args: |
   #       JAR_FILE=build/libs/demo-0.0.1-SNAPSHOT.jar
    #- name: Build and Push Docker Image
    #  uses: docker/build-push-action@v4
    #  with:
    #    push: true
    #    tags: mandriic/java-app:latest
