name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
        
    - name: Checkout repository
      uses: actions/checkout@v4
        

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'


    - name: Build with gradlew
      run: chmod +x ./gradlew && ./gradlew build
        
    - name: Archive Build Output
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build/libs/

    - name: Download Build Output
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: build/libs/
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        ecr: false
        username: ${{ secrets.DOCKERHUB_USERNAME }} 
        #password:  dckr_pat_Qxkv_-x2FWykZYsTbyqfCp2WxUw
        password: ${{ secrets.DOCKERHUB_TOKEN }} 
    
    - name: Set commit information (Optional usage)
      run: |
        COMMIT_SHA=$(git rev-parse --short=7 HEAD)
        COMMIT_MSG=$(git log -1 --pretty=%B | tr -d '\n')
        export TAG="commit-${COMMIT_SHA}-${COMMIT_MSG}"
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: mandriic/java-app:${{ github.sha }} , mandriic/java-app:latest
        file: Dockerfile
        build-args: |
          JAR_FILE=build/libs/demo-0.0.1-SNAPSHOT.jar

    - name: Update Image Tag Values
      run: |
        chart_dir="k8s"
        new_image_tag=${{ github.sha }}
        # Update version of docker image for triger argocd
        sed -i 's/mandriic\/java-app:.*/mandriic\/java-app:${{ github.sha }}/' k8s/java-app.yaml
    
    - name: Commit the changes made trig argoCD
      run: | 
        git config --global user.name 'mandriic'
        git config --global user.email 'kellaxxx@gmail.com'
        git add k8s/java-app.yaml
        git commit -am "updating image tag"
        git push
