name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      
jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Debug DockerHub Username Secret
        run: echo "DOCKERHUB_USERNAME ${{ secrets.DOCKERHUB_USERNAME }}"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Debug DockerHub Token Secret
        run: echo "DOCKERHUB_TOKEN ${{ secrets.DOCKERHUB_TOKEN }}"
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
